version: '3'
services:
  app:
    container_name: roofing-app
    restart: always
    build: .
    # env_file:
    #   - stack.env
    environment:
      REACT_APP_SUPABASE_URL: ${REACT_APP_SUPABASE_URL}
      REACT_APP_SUPABASE_KEY: ${REACT_APP_SUPABASE_KEY}
    expose:
      - 5173
    ports:
      - "5173:80"